apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  #annotations:
    #deployment.kubernetes.io/revision: "1"
  #creationTimestamp: "2019-10-11T12:30:46Z"
  #generation: 1
  labels:
    app: updayapp
  name: updayapp
  namespace: upday
  #resourceVersion: "10794"
  #selfLink: /apis/extensions/v1beta1/namespaces/upday/deployments/updayapp
  #uid: 8398f8c0-bbab-4dc3-b989-606e3919a78b
spec:
  #progressDeadlineSeconds: 600
  #replicas: 1
  replicas: 2
  #revisionHistoryLimit: 10
  selector:
    matchLabels:
      #app: updayapp
      run: helloworldapp 
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      #creationTimestamp: null
      labels:
        #app: updayapp
        run: helloworldapp
    spec:
      containers:
      - image: kuvivek/upday_helloworld:1.0
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        name: upday-helloworld
        #resources: {}
        #terminationMessagePath: /dev/termination-log
        #terminationMessagePolicy: File
      #dnsPolicy: ClusterFirst
      restartPolicy: Always
      #schedulerName: default-scheduler
      #securityContext: {}
      #terminationGracePeriodSeconds: 30
#status:
  #conditions:
  #- lastTransitionTime: "2019-10-11T12:30:47Z"
    #lastUpdateTime: "2019-10-11T12:30:47Z"
    #message: Deployment does not have minimum availability.
    #reason: MinimumReplicasUnavailable
    #status: "False"
    #type: Available
  #- lastTransitionTime: "2019-10-11T12:30:47Z"
    #lastUpdateTime: "2019-10-11T12:30:48Z"
    #message: ReplicaSet "updayapp-5c586c498b" is progressing.
    #reason: ReplicaSetUpdated
    #status: "True"
    #type: Progressing
  #observedGeneration: 1
  #replicas: 1
  #unavailableReplicas: 1
  #updatedReplicas: 1
