---
apiVersion: v1
kind: Namespace
metadata:
  name: upday
spec:
  finalizers:
  - kubernetes

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: updayapp
  name: updayapp
  namespace: upday
spec:
  #replicas: 1
  replicas: 2
  #revisionHistoryLimit: 10
  selector:
    matchLabels:
      #app: updayapp
      run: helloworldapp 
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        #app: updayapp
        run: helloworldapp
    spec:
      containers:
      - image: kuvivek/upday_helloworld:2.0
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        name: upday-helloworld
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: javaapp
  name: javaapp
  namespace: upday
spec:
  ports:
  - name: 80-8080
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    #app: javaapp
    run: helloworldapp
  type: NodePort

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: updayapp
  namespace: upday
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: updayapp
  targetCPUUtilizationPercentage: 50

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: pdb_upday
  namespace: upday
spec:
  minAvailable: 2
  selector:
    matchLabels:
      run: helloworldapp
