---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: updayapp
  namespace: upday
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: updayapp
  targetCPUUtilizationPercentage: 50
