---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: javaapp
  name: javaapp
  namespace: upday
spec:
  ports:
  - name: 80-8080
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    #app: javaapp
    run: helloworldapp
  type: NodePort
  #type: ClusterIP

